/**
 * Measured narration lengths, in seconds, keyed by scene id.
 *
 * GENERATED by `pnpm video:carlos:voiceover` — do not edit by hand. Empty means
 * no audio has been generated yet, and the compositions fall back to the
 * estimates in `script.ts` so a silent preview still renders.
 */
export const CARLOS_AUDIO_SECONDS: Readonly<Record<string, number>> = {
  "d1-problem": 7.11,
  "d1-questions": 12.98,
  "d1-optional": 6.87,
  "d1-brief": 9.2,
  "d1-catalogue": 11.6,
  "d1-operator": 6.16,
  "d1-enquiry": 7.89,
  "d1-question": 5.67,
  "d2-request": 8.44,
  "d2-days": 10.11,
  "d2-unknowns": 10.63,
  "d2-decision": 9.56,
  "d2-anonymous": 8.36,
  "d2-interest": 7.76,
  "d2-sharing": 9.01,
  "d2-receipt": 9.8,
  "d2-business": 10.03,
  "d2-question": 6.53,
  "d3-completed": 9.09,
  "d3-built": 14.71,
  "d3-truth": 10.58,
  "d3-gift": 8.39,
  "d3-souvenir": 8.59,
  "d3-future": 15.31,
  "d3-question": 5.38,
};
